### ISSUE TITLE
Update Description in DESCRIPTION

### ISSUE THREAD

**Issue by EmilHvitfeldt** [PPBDS/tidymodels.tutorials#31]
Hello 👋  Great work so far! Very excited to see how this progresses!

I had a small note, right now the `Description` field in the DESCRIPTION file uses the default value of `What the package does (one paragraph)`. This is being emitted when the link is shared.

![Screenshot 2023-08-07 at 9 49 56 AM](https://github.com/PPBDS/tidymodels.tutorials/assets/14034784/a1328c80-683a-49b0-93c1-f0edd84ec10a)

Not anything urgent, but will be nice to have fixed once it start getting shared online more frequently

**Comment by davidkane9** [comment]
Fixed. Thanks!
